export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const CALCULATE_ROI = 'CALCULATE_ROI';
export const SAVE_ROI = 'SAVE_ROI';
